services:
  db:
    container_name: pass-db
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - pass-network
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.25"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  account:
    container_name: pass-account
    image: localhost:${REGISTRY_PORT}/account:latest
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pass-network
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRING_POSTGRES}
      - JwtSettings__SecretKey=${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: "0.5"
        reservations:
          memory: 96M
          cpus: "0.25"

  vaultify:
    container_name: pass-vaultify
    image: localhost:${REGISTRY_PORT}/vaultify:latest
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pass-network
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRING_POSTGRES}
      - JwtSettings__SecretKey=${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: "0.5"
        reservations:
          memory: 96M
          cpus: "0.25"
  gw:
    container_name: pass-gw
    image: localhost:${REGISTRY_PORT}/gw:latest
    ports:
      - "${GW_PORT}:${GW_INTERNAL_PORT}"
    restart: unless-stopped
    networks:
      - pass-network
    volumes:
      - ./gateway/krakend.json:/etc/krakend/krakend.json:ro
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
        reservations:
          memory: 32M
          cpus: "0.1"

volumes:
  db-data:

networks:
  pass-network:
    external: true
    name: pass-network
