services:
  registry:
    container_name: pass-registry
    build:
      context: ./registry
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - pass-network
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    ports:
      - "${REGISTRY_PORT}:${REGISTRY_INTERNAL_PORT}"
    volumes:
      - ./registry/registry/data:/var/lib/registry
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
        reservations:
          memory: 32M
          cpus: "0.1"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${REGISTRY_PORT}/v2/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  server:
    container_name: pass-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - pass-network
    environment:
      - GW_INTERNAL_PORT=${GW_INTERNAL_PORT}
      - REGISTRY_INTERNAL_PORT=${REGISTRY_INTERNAL_PORT}
    volumes:
      - ./server/certs:/etc/nginx/certs
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
        reservations:
          memory: 32M
          cpus: "0.1"

networks:
  pass-network:
    external: true
    name: pass-network
