services:
  pass-registry:
    build:
      context: ./pass-registry
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - ./pass-registry/registry/data:/var/lib/registry
    deploy: #somente no build
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
        reservations:
          memory: 32M
          cpus: "0.1"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/v2/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    depends_on:
      pass-registry:
        condition: service_healthy
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.25"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  pass-api:
    image: localhost:5000/pass-api:latest
    depends_on:
      db:
        condition: service_healthy
      pass-registry:
        condition: service_healthy
    ports:
      - "8083:8080"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ConnectionStrings__Postgres=${CONNECTIONSTRING_POSTGRES}
      - JwtSettings__SecretKey=${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: "0.5"
        reservations:
          memory: 96M
          cpus: "0.25"
  pass-gw:
    build:
      context: pass-gw
      dockerfile: Dockerfile
    depends_on:
      pass-registry:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./pass-gw/krakend.json:/etc/krakend/krakend.json:ro
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
        reservations:
          memory: 32M
          cpus: "0.1"

  pass-client:
    build:
      context: pass-client
      dockerfile: Dockerfile
      target: build
    image: pass-client-build
    depends_on:
      pass-registry:
        condition: service_healthy

  pass-server:
    build:
      context: pass-server
      dockerfile: Dockerfile
    depends_on:
      pass-client:
        condition: service_completed_successfully
      pass-gw:
        condition: service_started
      pass-registry:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
        reservations:
          memory: 32M
          cpus: "0.1"

volumes:
  db-data:
