version: "3.8"

services:
  pass-registry:
    build:
      context: ./pass-registry
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./pass-registry/registry/data:/var/lib/registry
  db:
    image: postgres:15
    restart: unless-stopped
    depends_on:
      pass-registry:
        condition: service_healthy
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pass-api:
    image: pass-registry:5000/pass-api:latest
    depends_on:
      db:
        condition: service_healthy
      pass-registry:
        condition: service_healthy
    ports:
      - "8083:8080"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ConnectionStrings__Postgres=${CONNECTIONSTRING_POSTGRES}
      - JwtSettings__SecretKey=${JWT_SECRET}

  pass-gw:
    image: pass-registry:5000/pass-gw:latest
    depends_on:
      pass-registry:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./pass-gw/krakend.json:/etc/krakend/krakend.json:ro

  pass-client:
    image: pass-registry:5000/pass-client:latest
    depends_on:
      pass-registry:
        condition: service_healthy
    ports:
      - "80:80"
    restart: unless-stopped

  pass-server:
    build:
      context: pass-server
      dockerfile: Dockerfile
    depends_on:
      pass-registry:
        condition: service_healthy
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  db-data:
